### ISSUE TITLE
Image filenames

### ISSUE THREAD

**Issue by filaPro** [Simon4Yan/VisDA2020#1]
Hello,

Could you please provide more info about filenames?
Where is camera_id, person_id and what do other numbers mean in `0000_c1s1_001036_07.jpg` ?

Thank you.

**Comment by Simon4Yan** [comment]
Hi,

Thanks for your attention. 

Naming Rule of the bboxes.  In bbox "0046_c5s1_004279_02", "c5" is the 5-th camera (there 6 cameras in training and 5 cameras in testing). "s1" is sequence 1 of camera 5. 
"004279" is the4279-th frame in the sequence "c5s1". The frame rate is 25 frames per sec.
"0046" is the person ID.

As for the "0000_c1s1_001036_07.jpg", it is from the first camera, and its ID is 0000. Note that images of ID=0000 are detractors, which means these images do not belong to the same person. The ID=0000 only appears in the gallery of the test phase.

Moreover, we have provided a tiny code to read images and get camera & ID information:
https://github.com/Simon4Yan/VisDA2020/tree/master/devkit/data/datasets

Cheers!
