### ISSUE TITLE
the evaluation

### ISSUE THREAD

**Issue by SunskyF** [Simon4Yan/VisDA2020#3]
It seems that the mAP calculated by codelab is different from the local.
But rank-1 ~ rank-50 are the same.
Would you kindly give us a same evaluation code?

**Comment by Simon4Yan** [comment]
Thanks for your attention.

The mAP evaluation code in this github evaluates all matches.  And the server evaluates mAP based on top-100 matches (this is commonly used in the community, such as [Aitychallenge](https://www.aicitychallenge.org/2020-data-and-evaluation/)).

Thus, the CMC ranks are identical, while the mAP in the server is higher.  Consider the generality, I provide the code here to evaluate all matches. You could modify the evaluation code to evaluate the top-100 matches, if you want to calculate the same number of mAP with the codalab.

Regards!

**Comment by SunskyF** [comment]
Thanks for your reply!
