### ISSUE TITLE
使用默认的设置训练了，线上结果和线上对不上？

### ISSUE THREAD

**Issue by qianjinhao** [Simon4Yan/VisDA2020#4]
rank-1: 31.2997 rank-5: 46.6844 rank-10: 58.6207 rank-20: 69.7613 rank-50: 81.1671 mAP: 16.0786
运行了60epoch，上面是代码运行了test.py的输出结果，线上测试的结果都很低，map只有2.339569

**Comment by Simon4Yan** [comment]
Thanks for your attention.

I think you should check your codes of submission file generation. Please see the format requirement in [here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val).

Note that the matches should follow the rule that is "in ascending order of their distance to the query".

Good luck!

**Comment by qianjinhao** [comment]
> Thanks for your attention.
> 
> I think you should check your codes of submission file generation. Please see the format requirement in [here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val).
> 
> Note that the matches should follow the rule that is "in ascending order of their distance to the query".
> 
> Good luck!


    indices = np.argsort(q_g_dist, axis=1)
    np.savetxt("result.txt", indices[:, :100], fmt="%04d")
我用的是被注释的代码，现在这个比赛test没放出来，应该是推理target_validation吧，我有没有理解错误，第一次学习无监督reid，多多指教！

**Comment by Simon4Yan** [comment]
Hey!


You should make sure,
1)  "the first line of submission file is corresponding to the top 100 matches (represented as indices) of the first query (index=0000); the second line is corresponding to the second query (idex=0001)"; 

The indices of query images are [here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val).

2) after` indices = np.argsort(q_g_dist, axis=1) `, the resulting indices are "in ascending order of their distance to the query".

Please check the format ([here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val)) by yourself step by step. 

Thanks.

**Comment by qianjinhao** [comment]
> Hey!
> 
> You should make sure,
> 
> 1. "the first line of submission file is corresponding to the top 100 matches (represented as indices) of the first query (index=0000); the second line is corresponding to the second query (idex=0001)";
> 
> The indices of query images are [here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val).
> 
> 1. after`indices = np.argsort(q_g_dist, axis=1)`, the resulting indices are "in ascending order of their distance to the query".
> 
> Please check the format ([here](https://github.com/Simon4Yan/VisDA2020/tree/master/submit_val)) by yourself step by step.
> 
> Thanks.

谢谢你的回复，我现在知道怎么解决了！

**Comment by Simon4Yan** [comment]
Nice to hear that!

Good luck to the competition!
