### ISSUE TITLE
About the rule of the competition

### ISSUE THREAD

**Issue by vana77** [Simon4Yan/VisDA2020#5]
Hi @Simon4Yan , thanks for providing the useful information. I have some questions about the rule of the competition.
1. Can I use target_validation or target_test (which will be provided latter) for training without using their labels?
2. Can I use target_validation or target_test for re-ranking during evaluation?
3. Can I use camera index of target_train for training?
4. Can I use camera index of target_validation or target_test for re-ranking during evaluation?
Thanks!

**Comment by Simon4Yan** [comment]
Hi @vana77,

Thanks for your attention!

1. No. Don't use target validation/test_set for training.
2. Yes. Re-ranking is ok.
3. Yes. Camera indices are easy to get. 
4. Yes. Re-ranking with camera indices is allowed. 

Cheers!
