### ISSUE TITLE
Can we use personX_spgan in the challenge?

### ISSUE THREAD

**Issue by fandulu** [Simon4Yan/VisDA2020#6]
Can we use personX_spgan in the challenge?

**Comment by Simon4Yan** [comment]
Hi, thanks for your attention.

Yes, we already provided personX_SPGAN. 

The personX_spgan denotes the translated images from SPGAN. SPGAN conducts source-target image translation on personX, such that the translated images follow the distribution of the target. Thus, the Re-ID model trained on the translated images achieves high accuracy on the test set.

**Comment by fandulu** [comment]
thanks
